name: rive_splash_screen_plus
description: Facilitator for having a Splash screen with a Rive animation until some work has been done for the initialization of the app
version: 0.2.1
homepage: https://github.com/Khairul989/rive_splash_screen_plus

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.28.0"

dependencies:
  rive: ^0.14.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
