name: rive_splash_screen
description: Facilitator for having a Splash screen with a Rive animation until some work has been done for the initialization of the app
version: 0.1.1
homepage: https://github.com/jaumard/rive_splash_screen

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  rive_loading_plus: ^0.1.3
    #path: '../rive_loading_plus'
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
